### ISSUE TITLE
pip install geetools ERROR

### ISSUE THREAD

**Issue by gdellomonaco** [gee-community/gee_tools#12]
When I tryng to install the package i get out this issue:

Collecting geetools
  Using cached https://files.pythonhosted.org/packages/1d/57/f4d913a480480d44cfa94c78911b935dd40df2a2135be85d529741b21b91/geetools-0.1.1.tar.gz
Command "python setup.py egg_info" failed with error code 1 in C:\Users\xxxxx\AppData\Local\Temp\pip-install-ajxqlt3t\geetools\
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\xxxxxx\AppData\Local\Temp\pip-install-ajxqlt3t\geetools\setup.py", line 5, in <module>
        from geetools import __version__
      File "C:\Users\xxxxxxx\Local\Temp\pip-install-ajxqlt3t\geetools\geetools\__init__.py", line 20, in <module>
        from .ui.ipymap import Map
      File "C:\Users\GE899~1.DEL\AppData\Local\Temp\pip-install-ajxqlt3t\geetools\geetools\ui\__init__.py", line 12
        def eprint(eeobject, indent=2, notebook=False, async=False):
                                                                                       ^
    SyntaxError: invalid syntax

**Comment by PeterGriffioen** [comment]
If you change `async` to `do_async` or similar it works.

**Comment by fitoprincipe** [comment]
Has been already corrected in the `develop` branch (https://github.com/gee-community/gee_tools/commit/e457577d6fcc3fb077ff79fb3e3b4182b444a9b9)

**Comment by fitoprincipe** [comment]
How did it go @gdellomonaco ?

**Comment by sabogustavo** [comment]
Hello,
I have the same problem in ubuntu,
I did not understand what correction is necessary. And in what file.


Thank you
